name: Generate Daily Joke
run-name: Generating Daily Joke
on: 
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00
  workflow_dispatch:
jobs:
  generate-edit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run joke script
        run: |
          python src/joke.py
      - name: Commit README.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Generated Daily Joke"
          git push